services:
  web:
    build: .
    container_name: kurdleave_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=kurdleave
      - DB_USERNAME=kurdleave_user
      - DB_PASSWORD=kurdleave_pass

  mysql:
    image: mysql:8.0
    container_name: kurdleave_mysql
    restart: always
    environment:
      MYSQL_DATABASE: kurdleave
      MYSQL_USER: kurdleave_user
      MYSQL_PASSWORD: kurdleave_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kurdleave_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: kurdleave_user
      PMA_PASSWORD: kurdleave_pass
    depends_on:
      - mysql

volumes:
  mysql_data:
